In [1]:
import numpy as np

In [2]:
a = np.array([1,3])

In [3]:
type (a)

numpy.ndarray

In [4]:
a

array([1, 3])

In [5]:
np.zeroes((4,4))

AttributeError: module 'numpy' has no attribute 'zeroes'

In [6]:
np.zeros((4,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [7]:
np.ones((2,2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [8]:
np.ones((2,2), dtype = int) 

array([[1, 1],
       [1, 1]])

In [9]:
a = np.array([1,2])

In [10]:
np.log(a)

array([ 0.        ,  0.69314718])

In [11]:
np.exp(a)

array([ 2.71828183,  7.3890561 ])

In [14]:
b = np.array([2,2])

In [15]:
z=a.dot(b)

In [16]:
z=np.dot(a,b)

In [17]:
z

6